<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageType>Template</PackageType>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <NoWarn>$(NoWarn);NU5128;</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SadicAngel.Templates</PackageId>
    <Version>0.1.0</Version>
    <Authors>sadicangel</Authors>
    <Description>Personal .NET templates.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="templates/**/*" Exclude="templates/**/bin/**;templates/**/obj/**" />
    <Compile Remove="**/*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true" />
  </ItemGroup>

</Project>
